export const matches = [
    {
      leagueLogo: require('../assets/league_icons/league-1.png'),
      time: "87'",
      date:"1 August 2023",
      homeTeam: 'Man United',
      homeScore: 1,
      awayScore: 2,
      awayTeam: 'Man City',
      homeTeamLogo: require('../assets/league_icons/league-2.png'),
      awayTeamLogo: require('../assets/league_icons/league-3.png'),
    },
    {
      leagueLogo: require('../assets/league_icons/league-1.png'),
      homeTeam: 'Man United',
      date:"1 August 2023",
      time: "87'",
      homeScore: 1,
      awayScore: 2,
      awayTeam: 'Man City',
      homeTeamLogo: require('../assets/league_icons/league-2.png'),
      awayTeamLogo: require('../assets/league_icons/league-3.png'),
    },
    {
      leagueLogo: require('../assets/league_icons/league-1.png'),
      homeTeam: 'Man United',
      date:"1 August 2023",
      time: "87'",
      homeScore: 1,
      awayScore: 2,
      awayTeam: 'Man City',
      homeTeamLogo: require('../assets/league_icons/league-2.png'),
      awayTeamLogo: require('../assets/league_icons/league-3.png'),
    },
  ];